### ISSUE TITLE
채팅창을 열면 튕기는 문제

### ISSUE THREAD

**Issue by galdock** [ButterackingClient/ButterackingClient#2]
크래시 보고서는 다음과 같습니다.
`---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 24. 3. 30 오후 8:34
Description: Unexpected error

java.lang.ExceptionInInitializerError
	at net.minecraft.client.gui.GuiChat.initGui(GuiChat.java:437)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:469)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:4124)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:4924)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:4199)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3699)
	at net.minecraft.client.main.Main.main(Main.java:103)
Caused by: java.lang.NullPointerException
	at kp.Config.load(Config.java:32)
	at kp.Config.<clinit>(Config.java:18)
	... 7 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.client.gui.GuiChat.initGui(GuiChat.java:437)
	at net.minecraft.client.gui.GuiScreen.setWorldAndResolution(GuiScreen.java:469)
	at net.minecraft.client.Minecraft.displayGuiScreen(Minecraft.java:4124)

-- Affected level --
Details:
	Level name: MpServer
	All players: 9 total; [EntityPlayerSP['SeagullandEagle'/312578, l='MpServer', x=0.72, y=31.00, z=1.39], EntityOtherPlayerMP['21v9u191h6'/16, l='MpServer', x=22.50, y=28.00, z=5.50], EntityOtherPlayerMP['76721755g4'/67, l='MpServer', x=19.50, y=28.00, z=10.50], EntityOtherPlayerMP['q2d74klptc'/69, l='MpServer', x=22.59, y=28.00, z=-4.50], EntityOtherPlayerMP['cu3jfv85nf'/17, l='MpServer', x=32.50, y=29.00, z=-4.50], EntityOtherPlayerMP['d3r10d7u39'/19, l='MpServer', x=33.50, y=29.00, z=0.50], EntityOtherPlayerMP['e5l51tsn59'/20, l='MpServer', x=32.50, y=29.00, z=5.50], EntityOtherPlayerMP['v5d6ayozu7'/18, l='MpServer', x=38.50, y=29.00, z=-21.50], EntityOtherPlayerMP['t67eni0230'/68, l='MpServer', x=52.50, y=28.00, z=7.50]]
	Chunk stats: MultiplayerChunkCache: 150, 150
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: 0.00,31.00,1.00 - World: (0,31,1), Chunk: (at 0,1,1 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1180026115 game time, 136000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 81 total; [EntityPlayerSP['SeagullandEagle'/312578, l='MpServer', x=0.72, y=31.00, z=1.39], EntityOtherPlayerMP['t67eni0230'/68, l='MpServer', x=52.50, y=28.00, z=7.50], EntityArmorStand['§6Hytale 트레일러§r'/312579, l='MpServer', x=19.50, y=27.94, z=10.50], EntityOtherPlayerMP['21v9u191h6'/16, l='MpServer', x=22.50, y=28.00, z=5.50], EntityOtherPlayerMP['76721755g4'/67, l='MpServer', x=19.50, y=28.00, z=10.50], EntityOtherPlayerMP['21v9u191h6'/16, l='MpServer', x=22.50, y=28.00, z=5.50], EntityOtherPlayerMP['cu3jfv85nf'/17, l='MpServer', x=32.50, y=29.00, z=-4.50], EntityOtherPlayerMP['q2d74klptc'/69, l='MpServer', x=22.59, y=28.00, z=-4.50], EntityOtherPlayerMP['v5d6ayozu7'/18, l='MpServer', x=38.50, y=29.00, z=-21.50], EntityOtherPlayerMP['d3r10d7u39'/19, l='MpServer', x=33.50, y=29.00, z=0.50], EntityArmorStand['§b§l§n주간 UHC 우승'/147, l='MpServer', x=24.50, y=33.88, z=-29.50], EntityOtherPlayerMP['e5l51tsn59'/20, l='MpServer', x=32.50, y=29.00, z=5.50], EntityArmorStand['§7Solo'/148, l='MpServer', x=24.50, y=33.50, z=-29.50], EntityArmorStand['§e1. §6RoadRager§7 - §r§e15'/149, l='MpServer', x=24.50, y=33.00, z=-29.50], EntityBat['Bat'/22, l='MpServer', x=22.50, y=28.00, z=5.50], EntityArmorStand['§e2. §6tarlea§r§e [16]§7 - §r§e10'/150, l='MpServer', x=24.50, y=32.63, z=-29.50], EntityArmorStand['§e§l플레이어 1명'/23, l='MpServer', x=32.50, y=29.00, z=-4.50], EntityArmorStand['§e3. §6Leetamu§7 - §r§e8'/151, l='MpServer', x=24.50, y=32.25, z=-29.50], EntityArmorStand['§e4. §bqNova§r§e [16]§7 - §r§e8'/152, l='MpServer', x=24.50, y=31.88, z=-29.50], EntityArmorStand['§e5. §bOxha§r§2 [NOMS?]§7 - §r§e7'/153, l='MpServer', x=24.50, y=31.50, z=-29.50], EntityArmorStand['§e6. §6IplayLegitfr§r§e [CICADA]§7 - §r§e4'/154, l='MpServer', x=24.50, y=31.13, z=-29.50], EntityArmorStand['§e7. §6kzhy§7 - §r§e3'/155, l='MpServer', x=24.50, y=30.75, z=-29.50], EntityArmorStand['§e8. §6sirumair9505§r§e [16]§7 - §r§e3'/156, l='MpServer', x=24.50, y=30.41, z=-29.50], EntityOtherPlayerMP['d3r10d7u39'/19, l='MpServer', x=33.50, y=29.00, z=0.50], EntityArmorStand['§e9. §6Vska§7 - §r§e3'/157, l='MpServer', x=24.50, y=30.03, z=-29.50], EntityOtherPlayerMP['e5l51tsn59'/20, l='MpServer', x=32.50, y=29.00, z=5.50], EntityArmorStand['§e10. §bDlonay§r§7 [UHCGOD]§7 - §r§e3'/158, l='MpServer', x=24.50, y=29.66, z=-29.50], EntityArmorStand['§7아직 데이터가 없습니다.'/159, l='MpServer', x=24.50, y=29.28, z=-29.50], EntityArmorStand['§7Resets in a day and 1 hour.'/160, l='MpServer', x=24.50, y=28.75, z=-29.50], EntityArmorStand['§6설정을 변경하려면 클릭하세요!'/161, l='MpServer', x=24.50, y=28.38, z=-29.50], EntityArmorStand['§b§l§n주간 UHC 킬'/162, l='MpServer', x=30.50, y=33.88, z=-29.50], EntityArmorStand['§7Solo'/163, l='MpServer', x=30.50, y=33.50, z=-29.50], EntityArmorStand['§e1. §6RoadRager§7 - §r§e122'/164, l='MpServer', x=30.50, y=33.00, z=-29.50], EntityArmorStand['§e2. §6tarlea§r§e [16]§7 - §r§e109'/165, l='MpServer', x=30.50, y=32.63, z=-29.50], EntityArmorStand['§e3. §bqNova§r§e [16]§7 - §r§e88'/166, l='MpServer', x=30.50, y=32.25, z=-29.50], EntityArmorStand['§e4. §bOxha§r§2 [NOMS?]§7 - §r§e84'/167, l='MpServer', x=30.50, y=31.88, z=-29.50], EntityArmorStand['§e5. §6Leetamu§7 - §r§e58'/168, l='MpServer', x=30.50, y=31.50, z=-29.50], EntityArmorStand['§e6. §bisSpooky§7 - §r§e49'/169, l='MpServer', x=30.50, y=31.13, z=-29.50], EntityArmorStand['§e7. §6mnchpop§7 - §r§e48'/170, l='MpServer', x=30.50, y=30.75, z=-29.50], EntityArmorStand['§e8. §69237§r§e [?SURGE?]§7 - §r§e47'/171, l='MpServer', x=30.50, y=30.41, z=-29.50], EntityArmorStand['§e9. §6XDabysX§r§6 [CHAMP]§7 - §r§e46'/172, l='MpServer', x=30.50, y=30.03, z=-29.50], EntityArmorStand['§e10. §aPremixy§r§6 [FSVIER]§7 - §r§e44'/173, l='MpServer', x=30.50, y=29.66, z=-29.50], EntityArmorStand['§7아직 데이터가 없습니다.'/174, l='MpServer', x=30.50, y=29.28, z=-29.50], EntityArmorStand['§7Resets in a day and 1 hour.'/175, l='MpServer', x=30.50, y=28.75, z=-29.50], EntityArmorStand['§6설정을 변경하려면 클릭하세요!'/176, l='MpServer', x=30.50, y=28.38, z=-29.50], EntityArmorStand['§b§n순위표 설정'/177, l='MpServer', x=22.50, y=31.59, z=-25.50], EntityArmorStand['§7UHC Mode: §aSolo'/178, l='MpServer', x=22.50, y=31.13, z=-25.50], EntityArmorStand['§7Speed UHC Mode: §a모든 모드'/179, l='MpServer', x=22.50, y=30.75, z=-25.50], EntityArmorStand['§7시간: §a주간'/180, l='MpServer', x=22.50, y=30.41, z=-25.50], EntityArmorStand['§7보기 방식: §a상위 10위'/181, l='MpServer', x=22.50, y=30.03, z=-25.50], EntityArmorStand['§7플레이어: §a전체'/182, l='MpServer', x=22.50, y=29.66, z=-25.50], EntityArmorStand['§6설정을 변경하려면 클릭하세요!'/183, l='MpServer', x=22.50, y=29.28, z=-25.50], EntityVillager['Villager'/64, l='MpServer', x=19.50, y=28.00, z=-9.50], EntityArmorStand['§e§l우클릭'/65, l='MpServer', x=19.50, y=28.16, z=-9.50], EntityArmorStand['§b퀘스트 마스터'/66, l='MpServer', x=19.50, y=28.47, z=-9.50], EntityOtherPlayerMP['76721755g4'/67, l='MpServer', x=19.50, y=28.00, z=10.50], EntityOtherPlayerMP['t67eni0230'/68, l='MpServer', x=52.50, y=28.00, z=7.50], EntityOtherPlayerMP['q2d74klptc'/69, l='MpServer', x=22.59, y=28.00, z=-4.50], EntityBat['Bat'/71, l='MpServer', x=22.59, y=28.00, z=-4.50], EntityOtherPlayerMP['v5d6ayozu7'/18, l='MpServer', x=38.50, y=29.00, z=-21.50], EntityArmorStand['§e§l클릭하여 플레이'/80, l='MpServer', x=22.59, y=28.66, z=-4.50], EntityWither['§b§lSKY§f§lB§3§lLOCK 0.19.12 - TABLIST'/-1234, l='MpServer', x=33.69, y=30.32, z=0.73], EntityArmorStand['§6§lDUELS §bUHC'/81, l='MpServer', x=22.59, y=28.28, z=-4.50], EntityArmorStand['§e§l플레이어 46명'/82, l='MpServer', x=22.59, y=27.91, z=-4.50], EntityArmorStand['§b배달부'/83, l='MpServer', x=19.50, y=28.66, z=10.50], EntityArmorStand['§e§l우클릭'/84, l='MpServer', x=19.50, y=28.28, z=10.50], EntityArmorStand['§e§l우클릭'/89, l='MpServer', x=22.50, y=28.28, z=5.50], EntityArmorStand['§b제작법'/90, l='MpServer', x=22.50, y=27.91, z=5.50], EntityArmorStand['§6§l3x 코인'/91, l='MpServer', x=32.50, y=30.03, z=-4.50], EntityArmorStand['§e§l클릭하여 플레이'/92, l='MpServer', x=32.50, y=29.69, z=-4.50], EntityArmorStand['§bSpeed UHC'/93, l='MpServer', x=32.50, y=29.31, z=-4.50], EntityArmorStand['§e§l파쿠르 챌린지'/100, l='MpServer', x=-12.50, y=57.50, z=0.50], EntityArmorStand['§c§l완료'/101, l='MpServer', x=-12.50, y=57.13, z=0.50], EntityArmorStand['§6§l3x 코인'/106, l='MpServer', x=32.50, y=30.03, z=5.50], EntityArmorStand['§e§l클릭하여 플레이'/107, l='MpServer', x=32.50, y=29.69, z=5.50], EntityArmorStand['Armor Stand'/4331, l='MpServer', x=24.50, y=28.38, z=-29.50], EntityArmorStand['§bTeams of 3'/108, l='MpServer', x=32.50, y=29.31, z=5.50], EntityArmorStand['Armor Stand'/4332, l='MpServer', x=30.50, y=28.38, z=-29.50], EntityArmorStand['§e§l플레이어 0명'/109, l='MpServer', x=32.50, y=28.94, z=5.50], EntityArmorStand['§6§lUHC'/125, l='MpServer', x=27.50, y=35.25, z=-29.50], EntityArmorStand['§6§l순위표'/126, l='MpServer', x=27.50, y=34.88, z=-29.50]]
	Retry entities: 0 total; []
	Server brand: Hypixel BungeeCord (2024.3.3.1) <- vanilla
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.addWorldInfoToCrashReport(WorldClient.java:355)
	at net.minecraft.client.Minecraft.addGraphicsAndWorldToCrashReport(Minecraft.java:5364)
	at net.minecraft.client.Minecraft.run(Minecraft.java:3713)
	at net.minecraft.client.main.Main.main(Main.java:103)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 234594368 bytes (223 MB) / 436207616 bytes (416 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Butteracking Client v4
	LWJGL: 2.9.4
	OpenGL: AMD Radeon RX 6600 GL version 4.6.0 Compatibility Profile Context 24.10.00.34.240307, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor 
	OptiFine Version: OptiFine_1.8.9_HD_U_M5
	OptiFine Build: ~~NULL~~
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 Compatibility Profile Context 24.10.00.34.240307
	OpenGlRenderer: AMD Radeon RX 6600
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 12`
크래시 보고서에 따르면 채팅 관련 모듈에 문제가 생긴 것으로 보이는데, 정확히는 모르겠습니다.

**Comment by kmw0410** [comment]
다음버전때 해결된답니다
![image](https://github.com/ButterackingClient/ButterackingClient/assets/128137094/5012eda6-4f53-472e-a34a-4f8e5831108a)
